### ISSUE TITLE
Where to get wificfg?

### ISSUE THREAD

**Issue by astro** [ourairquality/oaq-esp-open-rtos#1]
Perhaps someone forgot to commit that?

**Comment by ourairquality** [comment]
See https://github.com/ourairquality/esp-open-rtos for the larger framework. A recursive clone of that includes this as an example.

**Comment by astro** [comment]
Thank you, I didn't know that you run your own rtos fork.

Are you going to send PRs to the upstream repo? Pretty please?

**Comment by wllang** [comment]
@astro Yes, most of it has been sent upstream to the esp-open-rtos repo. What remains have lower confidence but are rebased against upstream from time to time so it should be easy for people to adopt them on a branch - the master branch is the upstream master. At present rebasing seems blocked by the upstream SPI support which seems broken. This rebasing does make it hard to see the progress here, and harder to pull in the changes, so be sure to reset to the remote rebased tip.
