### ISSUE TITLE
How do I configure?

### ISSUE THREAD

**Issue by ferazambuja** [ourairquality/oaq-esp-open-rtos#2]
I was able to flash the example/oaq and the board shows on my wi-fi as OAQ_. It's password protected...
Noob here could find the how to edit the sysparam.

**Comment by ourairquality** [comment]
A default password is defined in the source code, see the following. You might want to change this default, and it is recommended to change the access point password in the configuration interface. https://github.com/ourairquality/oaq-esp-open-rtos/blob/30b6371bb3f8930af8a261bc768b60c420efd6f1/web.c#L1650

**Comment by ferazambuja** [comment]
Thanks
